# Generated by Django 3.0.3 on 2020-07-26 06:19

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of the post', max_length=300)),
                ('slug', models.SlugField(help_text='seo friendly title for the post', max_length=300, unique_for_date='date_published')),
                ('thumbnail', models.ImageField(help_text='image for the thubnail fo the post', upload_to=blog.models.upload_location)),
                ('content', models.TextField(help_text='body of your post')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('author', models.ForeignKey(help_text='select post author', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_published'],
            },
        ),
    ]
