# Generated by Django 3.0.3 on 2020-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('debian', 'DEBIAN'), ('ubuntu', 'UBUNTU'), ('redaht', 'REDHAT')], default='uncategorized', max_length=10),
        ),
    ]
