# Generated by Django 3.0.3 on 2020-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'UNCATEGORIZED'), ('debian', 'DEBIAN'), ('ubuntu', 'UBUNTU'), ('centos', 'CENTOS'), ('redaht', 'REDHAT')], default='uncategorized', max_length=20),
        ),
    ]
