# Generated by Django 3.0.3 on 2020-07-31 07:58

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200730_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
